"""empty message

Revision ID: 16eefd38f6fd
Revises: 4d076ba6505b
Create Date: 2024-07-13 18:46:28.173150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16eefd38f6fd'
down_revision = '4d076ba6505b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('heart_predictions', schema=None) as batch_op:
        batch_op.drop_constraint('heart_predictions_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('heart_predictions', schema=None) as batch_op:
        batch_op.create_unique_constraint('heart_predictions_email_key', ['email'])

    # ### end Alembic commands ###
